A role to create S3 bucket with Dynamodb table for Terraform Backend
redhat-cop/cloud.terraform_ops pull request #1
Opened 2023-12-13 17:40 UTC by abikouo

2024-01-08 19:33 UTC, hakbailey requested changes

2024-01-10 19:19 UTC, hakbailey commented on roles/aws_s3backend/templates/policy.json.j2
> +      "Resource": "arn:aws:s3:::{{ aws_s3backend_bucket_name }}/{{ aws_s3backend_terraform_state_path }}"
Shouldn't the above resources be switched in the if/else clause?

2024-01-10 19:19 UTC, hakbailey commented on tests/integration/targets/test_aws_s3backend/tasks/main.yml
> +
Could we also include tests that cover the IAM access granting and `aws_s3backend_terraform_state_path` conditions?

2024-01-10 19:19 UTC, hakbailey commented on roles/aws_s3backend/README.md
> +          aws_s3backend_dynamodb_table_name: db_state_lock
Could we include examples of all the variables just to be thorough?

2024-01-10 20:50 UTC, hakbailey commented
@abikouo I also noticed that the Jira ticket specified "The role should be able to either accept an existing IAM role to be granted the above permissions or create a new one", which this doesn't currently do. But I'm not sure if that's actually necessary. @gravesm do we think optionally creating a new IAM role for managing terraform state should be part of this role?

2024-01-11 14:32 UTC, abikouo commented on roles/aws_s3backend/templates/policy.json.j2
> +      "Resource": "arn:aws:s3:::{{ aws_s3backend_bucket_name }}/{{ aws_s3backend_terraform_state_path }}"
updated

2024-01-11 14:34 UTC, abikouo commented on roles/aws_s3backend/README.md
> +          aws_s3backend_dynamodb_table_name: db_state_lock
done

2024-01-11 15:48 UTC, abikouo commented on tests/integration/targets/test_aws_s3backend/tasks/main.yml
> +
@hakbailey this one cannot be tested in the CI due to policy limitation, we can update terminator policy to allow creation of user, role or group, this is not secured. As you can see, the following tests `iam_user`, `iam_role` and `iam_group` from the `amazon.aws` collection are marked as unsupported.

2024-01-11 19:57 UTC, gravesm commented on .github/workflows/integration.yml
> +        shell: bash
Can we use https://github.com/hashicorp/setup-terraform here?

2024-01-11 20:02 UTC, gravesm commented
> do we think optionally creating a new IAM role for managing terraform state should be part of this role?

Are there reasons we wouldn't want to? IMO an IAM role is going to be the most common way that people will use to handle access to the backend. There's a whole config section in the s3 backend dedicated to assume role functionality. It seems like it should be easy enough for us to create the role, and would make this much more useful.

2024-01-15 20:22 UTC, gravesm commented on roles/aws_s3backend/meta/argument_specs.yml
> +          - The user name, group name or role name of IAM resource you wish to grant access to S3 and DynamoDB.
We should probably include a note here that the user/group/role will be created if it does not exist.

2024-01-16 10:17 UTC, abikouo commented on roles/aws_s3backend/meta/argument_specs.yml
> +          - The user name, group name or role name of IAM resource you wish to grant access to S3 and DynamoDB.
done

2024-01-16 11:51 UTC, alinabuzachis commented on tox.ini
> +  black {toxinidir}/roles {toxinidir}/tests
Why should we change to {toxinidir}/roles?

2024-01-16 11:51 UTC, alinabuzachis commented on tox.ini
> +  black -v --check --diff {toxinidir}/roles {toxinidir}/tests
Same here.

2024-01-16 21:19 UTC, GomathiselviS commented on roles/aws_s3backend/README.md
> +- **aws_s3backend_delete_iam_resource**: On deletion, specifies whether the IAM resource (user, role or group) should be deleted along with the other resources (S3 bucket and DynamoDB table).
Is this a boolean? Can we specify the data type for all variables? It would be beneficial.

2024-01-18 15:28 UTC, hakbailey commented on tests/integration/targets/test_aws_s3backend/tasks/delete.yml
> +- name: Create S3 bucket for Terraform state storage
```suggestion
- name: Delete S3 bucket for Terraform state storage
```

2024-01-18 15:28 UTC, hakbailey commented on tests/integration/targets/test_aws_s3backend/tasks/main.yml
> +      ansible.builtin.include_tasks: create.yml
I think this should use the `delete.yml` task file?

2024-01-18 15:28 UTC, hakbailey commented on roles/aws_s3backend/tasks/role.yml
> +    state: present
This requires `assume_role_policy_document` when state=present.

2024-01-18 15:28 UTC, hakbailey commented on tests/integration/targets/test_aws_s3backend/tasks/main.yml
> +
Could we have tests here that are also marked as unsupported? Even if we can't run them in CI it would be good to have tests that can be run locally.

2024-01-18 15:28 UTC, hakbailey commented on roles/aws_s3backend/README.md
> +- **aws_s3backend_delete_iam_resource**: On deletion, specifies whether the IAM resource (user, role or group) should be deleted along with the other resources (S3 bucket and DynamoDB table).
Should we also note default values here?

2024-01-19 08:11 UTC, abikouo commented on roles/aws_s3backend/README.md
> +- **aws_s3backend_delete_iam_resource**: On deletion, specifies whether the IAM resource (user, role or group) should be deleted along with the other resources (S3 bucket and DynamoDB table).
@hakbailey the README has been updated accordingly

2024-01-19 09:15 UTC, abikouo commented on tests/integration/targets/test_aws_s3backend/tasks/main.yml
> +
@hakbailey I have added the corresponding test case

2024-01-19 14:32 UTC, gravesm approved these changes
Small change, otherwise LGTM.

2024-01-19 14:32 UTC, gravesm commented on README.md
> +The [amazon.aws](https://github.com/ansible-collections/amazon.aws) and [community.aws](https://github.com/ansible-collections/amazon.aws) collections MUST be installed in order for this collection t
This is only true for the S3 backend role, right? Probably worth being specific here.

2024-01-19 15:02 UTC, abikouo commented on README.md
> +The [amazon.aws](https://github.com/ansible-collections/amazon.aws) and [community.aws](https://github.com/ansible-collections/amazon.aws) collections MUST be installed in order for this collection t
Updated

2024-01-19 16:25 UTC, alinabuzachis approved these changes

2024-01-19 17:03 UTC, hakbailey approved these changes

2024-01-22 08:00 UTC, merged