[WIP] GCS gcs backend
redhat-cop/cloud.terraform_ops pull request #3
Opened 2024-01-19 22:24 UTC by mandar242

Add new role to create infrastructure required for GCS Terraform backend.

2024-01-22 08:13 UTC, abikouo requested changes

2024-01-22 08:13 UTC, abikouo commented on roles/gcs_backend/README.md
> +- operation - Choices include 'create' and 'delete'. `required`
```suggestion
- gcs_backend_operation - Choices include 'create' and 'delete'. `required`
```

2024-01-22 08:13 UTC, abikouo commented on roles/gcs_backend/README.md
> +- gcs_backend_service_account_file - The path of a Service Account JSON file if serviceaccount is selected as type. `required`
You should add a `gcs_backend_service_account_email` also, this is required when the `auth_kind` is set to `MachineAccount`

2024-01-22 08:13 UTC, abikouo commented on roles/gcs_backend/README.md
> +- gcs_backend_auth_kind - The type of credential used. Currently supports "serviceaccount". `required`
Why limiting support to service account ?

2024-01-22 08:13 UTC, abikouo commented on roles/gcs_backend/tasks/delete.yml
> +- name: Create a storage bucket with versioning enabled
```suggestion
- name: Delete a storage bucket
```

2024-01-22 08:13 UTC, abikouo commented on roles/gcs_backend/tasks/delete.yml
> +    state: absent
Note that this may fail when the storage bucket is not empty and the module does not support deleting non-empty bucket for now

2024-01-22 20:31 UTC, GomathiselviS commented on roles/gcs_backend/README.md
> +A role to ensure that the necessary GCP infrastructure is present for an Google Cloud Storage(GCS) remote backend for Terraform.
```suggestion
A role to ensure that the necessary GCP infrastructure is present for the Google Cloud Storage(GCS) remote backend for Terraform.
```

2024-01-22 21:09 UTC, GomathiselviS commented on roles/gcs_backend/README.md
> +## Role Variables
Can you also specify the data type of each variable?

2024-01-22 21:12 UTC, GomathiselviS commented on roles/gcs_backend/README.md
> +- gcs_backend_operation - Choices include 'create' and 'delete'. Note that `delete` operation might fail if bucket is non-empty. `required`
Should we have 'create' as the default value?

2024-01-22 21:17 UTC, GomathiselviS commented on roles/gcs_backend/tasks/main.yml
> +    - name: Ensure required parameters are proivided
We have to replace this check with meta/argument_specs.yml . Please refer [automation good practices](https://redhat-cop.github.io/automation-good-practices/#_argument_validation)

2024-01-23 15:22 UTC, GomathiselviS commented on roles/gcs_backend/README.md
> +
I believe it would be more cohesive to adhere to the format used by the documentation of azure_backend and aws_backend roles-https://github.com/redhat-cop/cloud.terraform_ops/tree/main/roles/aws_s3backend#role-variables.

2024-01-23 15:23 UTC, GomathiselviS commented on roles/gcs_backend/README.md
> +```
Please add the license and author information.

2024-01-23 15:26 UTC, GomathiselviS commented on roles/gcs_backend/README.md
> +- gcs_backend_operation (str) - Choices include 'create' and 'delete'. Note that `delete` operation might fail if bucket is non-empty. `required`
default: create

2024-01-23 15:29 UTC, GomathiselviS commented on roles/gcs_backend/meta/argument_specs.yml
> +          - Whether to create or delete the backend resources.
```suggestion
          - Whether to create or delete the backend resources.
          - Note that `delete` operation might fail if bucket is non-empty.
```

2024-01-23 15:32 UTC, GomathiselviS submitted a review, later dismissed
Please add defaults/main.yaml to include the default value for `gcs_backend_operation`. You should also include this role in https://github.com/redhat-cop/cloud.terraform_ops/blob/main/README.md#roles

2024-01-23 20:12 UTC, GomathiselviS commented on README.md
> +[cloud.terraform_ops.gcs_backend](https://github.com/ansible-collections/cloud.terraform_ops/blob/main/roles/gcs_backend/README.md)|A role to create the necessary Google Cloud infrastructure for an G
```suggestion
[cloud.terraform_ops.gcs_backend](https://github.com/redhat-cop/cloud.terraform_ops/blob/main/roles/gcs_backend/README.md)|A role to create the necessary Google Cloud infrastructure for an GCS remote backend for Terraform.
```

2024-01-23 20:13 UTC, GomathiselviS commented on README.md
>  [cloud.terraform_ops.aws_s3backend](https://github.com/ansible-collections/cloud.terraform_ops/blob/main/roles/aws_s3backend/README.md)|A role to create the necessary AWS infrastructure for an S3 rem
```suggestion
[cloud.terraform_ops.aws_s3backend](https://github.com/redhat-cop/cloud.terraform_ops/blob/main/roles/aws_s3backend/README.md)|A role to create the necessary AWS infrastructure for an S3 remote backend for Terraform.
```

2024-01-24 14:33 UTC, GomathiselviS commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
Why should we ignore errors here?

2024-01-24 18:06 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
if bucket is not present, the command fails causing playbook to fail at that task
I thought of having a `assert` on the `bucket_info` would provide cleaner failure with `assertion failure` if bucket is not present

2024-01-24 18:08 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
although I'm fine with either way, would you recommend removing ignore errors and letting playbook fail at gcloud command task?

2024-01-24 19:10 UTC, GomathiselviS commented on tests/integration/requirements.yml
> +    version: main
should this be master?

2024-01-24 19:14 UTC, GomathiselviS commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
Based on [this link](https://ansible.readthedocs.io/projects/lint/rules/ignore-errors/), it seems that ansible-lint would generate an error for this line. Could we consider using one of the recommended methods mentioned in the link?

2024-01-24 19:15 UTC, GomathiselviS commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
Consider changing this as well

2024-01-24 19:23 UTC, GomathiselviS commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      register: delete_file_result
I think this variable should be asserted.

2024-01-24 19:23 UTC, GomathiselviS commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      register: delete_bucket_result
same here

2024-01-24 19:24 UTC, GomathiselviS commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
Consider changing this.

2024-01-24 20:11 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
one of the examples under `correct code` in the link uses `register`, I think the current code should work as it has `register` wherever there is `ignore_errors`
```
---
- name: Example playbook
  hosts: all
  tasks:
    - name: Run apt-get update
      ansible.builtin.command: apt-get update
      ignore_errors: true
      register: ignore_errors_register # <- Stores errors and failures for evaluation.
```

2024-01-24 20:34 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      register: delete_bucket_result
added note above test about the `expected failure` in the task

2024-01-24 20:34 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      register: delete_file_result
added assertion

2024-01-24 20:35 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
https://github.com/redhat-cop/cloud.terraform_ops/pull/3/files#r1465485302

2024-01-24 20:36 UTC, mandar242 commented on tests/integration/requirements.yml
> +    version: main
changed, thanks!

2024-01-26 15:54 UTC, abikouo requested changes

2024-01-26 15:54 UTC, abikouo commented on changelogs/fragments/3-gcs_backend-add-role-for-creating-gcs-backend.yml
> +---
A changelog is not necessary as there is no release yet on this collection

2024-01-26 15:54 UTC, abikouo commented on roles/gcs_backend/README.md
> +gcs_backend_auth_kind|The type of credential used|string|N/A| Yes
We should list supported values here (application, machineaccount, serviceaccount)

2024-01-26 15:54 UTC, abikouo commented on roles/gcs_backend/README.md
> +gcs_backend_service_account_file|The path of a Service Account JSON file if serviceaccount is selected as type.|string|N/A| when `gcs_backend_auth_kind = serviceaccount`
```suggestion
gcs_backend_service_account_file|The path of a Service Account JSON file if serviceaccount is selected as authentication type.|string|N/A| when `gcs_backend_auth_kind = serviceaccount`
```

2024-01-26 15:54 UTC, abikouo commented on roles/gcs_backend/README.md
> +gcs_backend_service_account_email|The service account email used for authentication.|string|N/A| when `gcs_backend_auth_kind = machineaccount`
```suggestion
gcs_backend_service_account_email|An optional service account email address if machineaccount is selected and the user does not wish to use the default email.|string|N/A| No
```

This parameter is not required, even when the auth_kind is set to machineaccount, it offers extra options

2024-01-26 15:54 UTC, abikouo commented on roles/gcs_backend/meta/argument_specs.yml
> +          - required when `gcs_backend_auth_kind = machineaccount`.
```suggestion
          - An optional service account email address if machineaccount is selected and the user does not wish to use the default email.
```

2024-01-26 15:54 UTC, abikouo commented on roles/gcs_backend/tasks/delete.yml
> +  ignore_errors: true  # currently module `gcp_storage_bucket` does not support deleting non-empty buckets
You can register the task result and in case it failed display a debug message informing the user that the it needs to manually remove objects from the storage account and either re-run the role or delete it manually
This should not been kept only in the code

2024-01-26 15:54 UTC, abikouo commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
@mandar242 please do not use any occurrence of `gcloud` cli anywhere.
You can either create a new info module into the google.cloud collection (I dont if we are authorized to do so), create a local python script or ansible module intended to be used only for this integration test target, or a quick an dirty solution is calling again `google.cloud.gcp_storage_bucket` with the same storage bucket name and ensure the module did not reported any changes
Another possible solution to validate that the Storage bucket has been created is to run a terraform configuration using this storage bucket as configuration and then you can use the `gcp_storage_object` with the `download` option to ensure that the state file has been stored

2024-01-26 15:54 UTC, abikouo commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
Same as comment above for the `gcloud` cli

2024-01-26 19:57 UTC, mandar242 commented on roles/gcs_backend/tasks/delete.yml
> +  ignore_errors: true  # currently module `gcp_storage_bucket` does not support deleting non-empty buckets
Added

2024-01-26 19:57 UTC, mandar242 commented on roles/gcs_backend/meta/argument_specs.yml
> +          - required when `gcs_backend_auth_kind = machineaccount`.
Fixed

2024-01-26 19:57 UTC, mandar242 commented on roles/gcs_backend/README.md
> +gcs_backend_service_account_email|The service account email used for authentication.|string|N/A| when `gcs_backend_auth_kind = machineaccount`
Fixed

2024-01-26 19:57 UTC, mandar242 commented on roles/gcs_backend/README.md
> +gcs_backend_service_account_file|The path of a Service Account JSON file if serviceaccount is selected as type.|string|N/A| when `gcs_backend_auth_kind = serviceaccount`
Fixed

2024-01-26 19:58 UTC, mandar242 commented on roles/gcs_backend/README.md
> +gcs_backend_auth_kind|The type of credential used|string|N/A| Yes
Fixed

2024-01-26 19:58 UTC, mandar242 commented on changelogs/fragments/3-gcs_backend-add-role-for-creating-gcs-backend.yml
> +---
Removed. Had added it to stop ci failing on `Changelog / test / Require a changelog (pull_request)`

2024-01-26 20:02 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
fixed, thanks!

2024-01-29 09:44 UTC, abikouo requested changes
Looks good overall, but just few remaining items to fix

2024-01-29 09:44 UTC, abikouo commented on roles/gcs_backend/meta/argument_specs.yml
> +          - required when `gcs_backend_auth_kind = machineaccount`.
```suggestion
         
```

2024-01-29 09:44 UTC, abikouo commented on tests/integration/targets/test_gcs_backend/files/force_delete_bucket.py
> +def delete_bucket(bucket_name, project_name, credentials_file_path):
The `credentials_file_path` parameter is not used in the function, I am not sure this code is working without authentication

2024-01-29 16:40 UTC, hakbailey requested changes

2024-01-29 16:40 UTC, hakbailey commented on tests/integration/targets/test_gcs_backend/defaults/main.yml
> +test_gcs_backend_bucket_name: gcs-backend-integration-test-bucket
This should probably use `resource_prefix` so test buckets have unique names.

2024-01-29 16:40 UTC, hakbailey commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
I also don't understand why we are ignoring errors here.

2024-01-29 16:40 UTC, hakbailey commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
Rather than ignoring all errors here, I think we should define `failed_when` so that it will fail if the error is anything other than `'The bucket you tried to delete is not empty.'`

2024-01-29 17:15 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
@hakbailey code that was using `gcloud cli` has been removed. I had forgot to resolve this conversation 😅

2024-01-29 17:25 UTC, mandar242 commented on roles/gcs_backend/tasks/delete.yml
> +      - "Deleting non-empty buckets might fail currently and buckets should be deleted manually."
I thought of not specifying this as
- currently, fails as google.cloud.gcp_storage_bucket module does not support force delete non-empty bucket
- object deletion does not help as buckets with versioning enabled retain the deleted objects, again causing module to fail deletion

2024-01-29 19:13 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/defaults/main.yml
> +GCP_PROJECT_ID: "project-123-dev"
removed.

2024-01-29 19:13 UTC, mandar242 commented on roles/gcs_backend/tasks/delete.yml
> +      - "Please refer following error message for more details."
fixed.

2024-01-29 19:14 UTC, mandar242 commented on roles/gcs_backend/README.md
> +A role to ensure that the necessary GCP infrastructure is present for the Google Cloud Storage(GCS) remote backend for Terraform.
fixed.

2024-01-29 19:14 UTC, mandar242 commented on README.md
> +[cloud.terraform_ops.gcs_backend](https://github.com/redhat-cop/cloud.terraform_ops/blob/main/roles/gcs_backend/README.md)|A role to create the necessary Google Cloud infrastructure for an GCS remote
fixed.

2024-01-29 19:14 UTC, mandar242 commented on roles/gcs_backend/meta/argument_specs.yml
> +          - required when `gcs_backend_auth_kind = machineaccount`.
fixed.

2024-01-29 19:18 UTC, mandar242 commented on README.md
> +The [amazon.aws](https://github.com/ansible-collections/amazon.aws) and [community.aws](https://github.com/ansible-collections/amazon.aws) collections MUST be installed to use the role [cloud.terrafo
yes, added.

2024-01-29 19:18 UTC, mandar242 commented on roles/gcs_backend/meta/argument_specs.yml
> +    short_description: A role to create/delete the GCP infrastructure for an GCS remote backend for Terraform.
fixed.

2024-01-29 19:18 UTC, mandar242 commented on roles/gcs_backend/tasks/delete.yml
> +  ansible.builtin.debug:
fixed.

2024-01-29 19:27 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
removed `ignore_errors` from tests, added to role task for delete operations
this will not `fail` the tests and at the same time display error message when role is ran to notify user to delete manually

2024-01-29 19:58 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +        auth_kind: serviceaccount
as gcp tests don't run in CI, I'm not sure if that would work
although I'm probably missing something here, could you please elaborate how to do this

2024-01-29 19:59 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/files/force_delete_bucket.py
> +def delete_bucket(bucket_name, project_name, credentials_file_path):
fixed.

2024-01-29 21:37 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +        auth_kind: serviceaccount
added

2024-01-30 15:13 UTC, alinabuzachis commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ansible.builtin.script: force_delete_bucket.py
Does the role support deleting non empty buckets with this script?

2024-01-30 15:16 UTC, alinabuzachis commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ansible.builtin.script: force_delete_bucket.py
If yes, you should now remove anything mentioning that it does only delete empty buckets.

2024-01-30 16:42 UTC, hakbailey commented on roles/gcs_backend/tasks/delete.yml
> +      - "Deleting non-empty buckets might fail currently and buckets should be deleted manually."
Ah got it, make sense to leave as is then!

2024-01-30 16:56 UTC, hakbailey commented on roles/gcs_backend/tasks/delete.yml
> +  ignore_errors: true
Hmm, I don't think we want to ignore errors here. This is in fact a failure, and should be presented to the user as such.

2024-01-30 18:00 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ansible.builtin.script: force_delete_bucket.py
unfortunately it does not support deleting non-empty buckets as
1. module `google.cloud.gcp_storage_bucket` does not support deleting non-empty buckets
2. even if we try approach of firstly emptying bucket and then deleting with same module, it fails because buckets with `object version enabled` keep a copy of deleted object as well, this fails the deleting again.

2024-01-30 18:01 UTC, mandar242 commented on roles/gcs_backend/README.md
> +gcs_backend_operation|Whether to create or delete the Backend resources (GCS bucket). Choices: 'create', 'delete'.  Note that `delete` operation might fail if bucket is non-empty.|string|create| N/A
yes, it is mentioned already 
<img width="1008" alt="image" src="https://github.com/redhat-cop/cloud.terraform_ops/assets/29326601/e841605b-1d3b-45a1-8871-135c3c11c15f">

2024-01-30 20:31 UTC, hakbailey commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
I think we do have to ignore_errors here, sorry for the confusion! I was trying to figure out a way to only ignore the error we are expecting but apparently `failed_when` doesn't work with role includes.

2024-01-30 21:18 UTC, mandar242 commented on tests/integration/targets/test_gcs_backend/tasks/main.yml
> +      ignore_errors: true
adding `ignore_errors` in the test task below would still cause tests to fail as this task in roles/gcs_backend/tasks/delete.yml https://github.com/redhat-cop/cloud.terraform_ops/pull/3/files#diff-266ad447cb12fecdb0ca92156ec232d1a9aac87e9b8878c750ac9ee182997419R12-R18 does not `ignore` errors (error is expected due to being unable to delete non-empty buckets)
```
    - name: Delete GCS backend resources
      ansible.builtin.include_role:
        name: cloud.terraform_ops.gcs_backend
      vars:
        gcs_backend_operation: delete
        ...
```
are we okay with this behavior in tests? also `ignore_errors` does not work on `include_role` if task inside the role fails, it fails

2024-01-31 16:58 UTC, alinabuzachis approved these changes

2024-02-05 14:31 UTC, abikouo approved these changes

2024-02-05 18:11 UTC, gravesm approved these changes

2024-02-05 20:11 UTC, merged