GCS Backend: minor fixes for auth when using role with AAP controller
redhat-cop/cloud.terraform_ops pull request #4
Opened 2024-02-14 00:18 UTC by mandar242

gcs_backend role can be used with AAP Controller without providing `service_account_file` and `service_account_email`.
This requires adding GCE credentials in the controller and providing that to job template.

This PR makes minor fixes and updates readme to reflect the above.

2024-02-14 07:56 UTC, abikouo requested changes
The controller will also populate env variables for the GCP Project and Auth_kind
See https://github.com/ansible/awx/blob/38424487f1a46c97ce34c2168bf641a1ff49a0d2/awx/main/models/credential/injectors.py#L44-L45

2024-02-14 07:56 UTC, abikouo commented on roles/gcs_backend/tasks/create.yml
>      auth_kind: "{{ gcs_backend_auth_kind }}"
```suggestion
    project: "{{ gcs_backend_gcp_project | default(omit) }}"
    auth_kind: "{{ gcs_backend_auth_kind | default(omit) }}"
```

2024-02-14 07:56 UTC, abikouo commented on roles/gcs_backend/tasks/delete.yml
>      auth_kind: "{{ gcs_backend_auth_kind }}"
```suggestion
    project: "{{ gcs_backend_gcp_project | default(omit) }}"
    auth_kind: "{{ gcs_backend_auth_kind | default(omit) }}"
```

2024-02-14 14:20 UTC, gravesm commented on roles/gcs_backend/README.md
> +Note: When using this role in AAP Controller, authentication to Google Cloud Platform (GCP) can be performed by adding GCE type credentials in AAP Controller and providing it to the job template that
```suggestion
### Using with Ansible Automation Platform (AAP)

Note: When using this role in AAP, authentication to Google Cloud Platform (GCP) can be performed by adding GCE type credentials in AAP and providing it to the job template that makes use of this role.
```

2024-02-15 19:24 UTC, alinabuzachis approved these changes

2024-02-15 19:36 UTC, merged