new role: plan_stash
redhat-cop/cloud.terraform_ops pull request #8
Opened 2024-03-13 02:15 UTC by mandar242

Adding new role to demonstrate usage of [cloud.terraform.plan_stash](https://github.com/ansible-collections/cloud.terraform/blob/main/plugins/modules/plan_stash.py) module.

-----------
### Testing (Latest):

This role ideally should be ran on AWX (controller/tower).
[Latest Testing on controller 03/14]
- Playbooks used in dev testing can be referred:
[module_plan_stash_role_stash_test_2.yml](https://github.com/mandar242/Test-Playbooks/blob/main/module_plan_stash_role_stash_test_2.yml)
[module_plan_stash_role_load_test_2.yml](https://github.com/mandar242/Test-Playbooks/blob/main/module_plan_stash_role_load_test_2.yml)

- Workflow ran on controller: [https://controller.ansiblecloud.xyz/#/jobs/workflow/495/output
](https://controller.ansiblecloud.xyz/#/jobs/workflow/495/output)

##### Outputs

When the workflow is run, below actions take place
- The [first playbook used in workflow](https://github.com/mandar242/Test-Playbooks/blob/main/module_plan_stash_role_stash_test_2.yml) stores b64encoded Terraform Plan into ansible stats (Artifacts) named `my_test_stashed_plan` i.e. "{{ module_plan_stash_var_name_val }}"
- The [second playbook used in workflow](https://github.com/mandar242/Test-Playbooks/blob/main/module_plan_stash_role_load_test_2.yml) uses artificats from first playbook to pass b64encoded plan as variable named `my_test_stashed_plan` i.e. "{{ module_plan_stash_var_name_val }}"
- The[second playbook used in workflow](https://github.com/mandar242/Test-Playbooks/blob/main/module_plan_stash_role_load_test_2.yml) loads the variable and creates a file I(module_plan_stash_plan_file_path) and writes the Terraform Plan to it, which can be used further through collections such as [cloud.terraform collection](https://github.com/ansible-collections/cloud.terraform)
Refer README for the role for more info.

-----------
### Testing (Outdated):

This role ideally should be ran on AWX (controller/tower).
[Latest Testing on controller 03/13]
- Playbooks used in dev testing can be referred:
[module_plan_stash_role_stash_test_2.yml](https://github.com/mandar242/Test-Playbooks/blob/main/module_plan_stash_role_stash_test_2.yml)
[module_plan_stash_role_load_test_2.yml](https://github.com/mandar242/Test-Playbooks/blob/main/module_plan_stash_role_load_test_2.yml)

- Workflow ran on controller: https://controller.ansiblecloud.xyz/#/jobs/workflow/453/output

##### Outputs

When the workflow is run, below actions take place
- The [first playbook used in workflow](https://github.com/mandar242/Test-Playbooks/blob/main/module_plan_stash_role_stash_test_2.yml) stores b64encoded Terraform Plan into ansible stats (Artifacts) named `my_test_stashed_plan` i.e. "{{ module_plan_stash_var_name_val }}"
- The [second playbook used in workflow](https://github.com/mandar242/Test-Playbooks/blob/main/module_plan_stash_role_load_test_2.yml) uses artificats from first playbook to pass b64encoded plan as variable named `my_test_stashed_plan` i.e. "{{ module_plan_stash_var_name_val }}"
- The[second playbook used in workflow](https://github.com/mandar242/Test-Playbooks/blob/main/module_plan_stash_role_load_test_2.yml) loads the variable and creates a file I(module_plan_stash_plan_file_path) and writes the Terraform Plan to it, which can be used further through collections such as [cloud.terraform collection](https://github.com/ansible-collections/cloud.terraform)
Refer README for the role for more info.

2024-03-13 15:45 UTC, abikouo requested changes
Could you please add `meta/argument_specs.yml` for the role? and if possible some integration tests to validate this new role

2024-03-13 15:45 UTC, abikouo commented on roles/module_plan_stash/README.md
> +A role to handle the base64 encoding or decoding of a terraform plan file using cloud.terraform.plan_stash module.
Regarding to what has been implemented this is not true, the role is doing more that just stashing the terraform plan file, it also generate the plan using `cloud.terraform.terraform` but this should be exclude from the scope

2024-03-13 15:45 UTC, abikouo commented on roles/module_plan_stash/README.md
> +module_plan_stash_tf_project_path|The path to terraform project directory containing configuration file|path|false|false
```suggestion
```
This is not required, we just need a path to a plan file from/to which the data will be decoded/encoded

2024-03-13 15:45 UTC, abikouo commented on roles/module_plan_stash/README.md
> +module_plan_stash_plan_file_path|-The path to the terraform plan file. -When I(module_plan_stash_generate_plan_file=True), I(module_plan_stash_plan_file_path) will be used to store generated plan fil
```suggestion
module_plan_stash_plan_file_path|-The path to the terraform plan file.|path|N/A|true
```
This will be used for both encoding/decoding plan file depending on the value set into `module_plan_stash_operation`

2024-03-13 15:45 UTC, abikouo commented on roles/module_plan_stash/README.md
> +module_plan_stash_generate_plan_file|Whether to generate plan file from Terraform config to use when doing stash plan|bool|false|false
```suggestion
```
This is a useless parameter

2024-03-13 15:45 UTC, abikouo commented on roles/module_plan_stash/README.md
> +- When I(module_plan_stash_generate_plan_file_val) is set to False, I(terraform_existing_plan_url) must be provided.
```suggestion
```

2024-03-13 15:45 UTC, abikouo commented on roles/module_plan_stash/README.md
> +```
```suggestion
First create playbook below to stash the terraform plan and store it to ansible stats into variable "my_test_stashed_plan"
```
---
- hosts: localhost
  gather_facts: false

  roles:
    - role: cloud.terraform_ops.module_plan_stash
      module_plan_stash_operation: stash
      module_plan_stash_var_name: "my_test_stashed_plan" # if not provided, defaults to "terraform_plan"
      module_plan_stash_plan_file_path: "path_to_my_terraform_plan_file"
```
```

2024-03-13 15:45 UTC, abikouo commented on roles/module_plan_stash/README.md
> +            path: "{{ tfdir.path }}"
```suggestion
---
- name: Test the cloud.terraform_ops.module_plan_stash role (load functionality)
  hosts: localhost
  gather_facts: false
  
  roles:
    - roles: cloud.terraform_ops.module_plan_stash
      module_plan_stash_operation: load
      module_plan_stash_var_name: "my_test_stashed_plan" # if not provided, defaults to "terraform_plan"
      module_plan_stash_plan_file_path: "path_to_my_plan_file"

      always:
        - name: Delete temporary directory
          ansible.builtin.file:
            state: absent
            path: "{{ tfdir.path }}"
```

2024-03-13 15:45 UTC, abikouo commented on roles/module_plan_stash/tasks/stash.yml
> +  when: module_plan_stash_generate_plan_file == True
```suggestion
```

2024-03-14 00:32 UTC, mandar242 commented on roles/module_plan_stash/README.md
> +module_plan_stash_tf_project_path|The path to terraform project directory containing configuration file|path|false|false
removed `module_plan_stash_tf_project_path`

2024-03-14 00:33 UTC, mandar242 commented on roles/module_plan_stash/README.md
> +- When I(module_plan_stash_generate_plan_file_val) is set to False, I(terraform_existing_plan_url) must be provided.
removed

2024-03-14 00:34 UTC, mandar242 commented on roles/module_plan_stash/README.md
> +```
fixed example

2024-03-14 00:35 UTC, mandar242 commented on roles/module_plan_stash/tasks/stash.yml
> +  when: module_plan_stash_generate_plan_file == True
removed

2024-03-14 00:35 UTC, mandar242 commented on roles/module_plan_stash/README.md
> +A role to handle the base64 encoding or decoding of a terraform plan file using cloud.terraform.plan_stash module.
removed

2024-03-14 11:28 UTC, abikouo requested changes

2024-03-14 11:28 UTC, abikouo commented on roles/module_plan_stash/tasks/load.yml
> +    binary_data: "{{ binary_data | default(omit) }}"
```suggestion
```
there is no `binary_data` parameter defined in the role parameters

2024-03-14 17:35 UTC, gravesm commented on roles/module_plan_stash/README.md
> +# module_plan_stash
Could we rename this to just "plan_stash"? Some of the options are pretty wordy to type.

2024-03-14 17:40 UTC, mandar242 commented on roles/module_plan_stash/README.md
> +# module_plan_stash
renamed

2024-03-14 17:49 UTC, mandar242 commented on roles/module_plan_stash/README.md
> +## Example Playbook
something like this right?
I'll do more testing before adding it to docs

```
---
- name: Test the cloud.terraform_ops.plan_stash role (load functionality)
  hosts: localhost
  gather_facts: false
  vars:
    plan_stash_var_name_val: my_test_stashed_plan
    plan_stash_plan_file_path_val: /path/to/plan/file/to/load/create/loaded.tfplan
  tasks:
    - name: Load the Terraform plan from variable "{{ plan_stash_var_name_val }}" into file "{{ plan_stash_plan_file_path_val }}"
      ansible.builtin.include_role:
        name: cloud.terraform_ops.plan_stash
      vars:
        plan_stash_operation: load
        plan_stash_var_name: "{{ plan_stash_var_name_val }}" # if not provided, defaults to "terraform_plan"
        plan_stash_plan_file_path: "{{ plan_stash_plan_file_path_val }}" #"path_to_my_plan_file"

    - name: Apply the Terraform configuration
      cloud.terraform.terraform:
        project_path: "."
        force_init: true
        plan_file: "{{ plan_stash_plan_file_path_val }}"
        state: present
```

2024-03-15 00:02 UTC, mandar242 commented on roles/module_plan_stash/README.md
> +## Example Playbook
added examples.

2024-03-15 09:44 UTC, abikouo requested changes

2024-03-15 09:44 UTC, abikouo commented on roles/plan_stash/tasks/load.yml
> +    binary_data: "{{ binary_data | default(omit) }}"
```suggestion
```
You need to remove this!!

2024-03-15 18:37 UTC, mandar242 commented on roles/module_plan_stash/tasks/load.yml
> +    binary_data: "{{ binary_data | default(omit) }}"
removed.

2024-03-15 18:37 UTC, mandar242 commented on roles/plan_stash/tasks/load.yml
> +    binary_data: "{{ binary_data | default(omit) }}"
removed

2024-03-18 10:58 UTC, abikouo approved these changes

2024-03-18 17:51 UTC, gravesm approved these changes

2024-03-18 19:33 UTC, merged